const canvas = document.getElementById('geometry-canvas');
const ctx = canvas.getContext('2d');
const ui = {
  count: document.getElementById('step-count'), title: document.getElementById('instruction-title'), copy: document.getElementById('instruction-copy'),
  message: document.getElementById('canvas-message'), badge: document.getElementById('parallel-badge'), relationship: document.getElementById('relationship'), undo: document.getElementById('undo'),
  labels: [...document.querySelectorAll('.canvas-label')]
};
const C = { orange:'#f36f45', blue:'#3f73c9', dark:'#172d3d', lime:'#d8e976', purple:'#9a62cf', muted:'#9ba7a4' };
let dpr = window.devicePixelRatio || 1;
let state;

function freshState() { return { lines:[], phase:0, drawStart:null, pointer:null, draggingHandle:false, draggingTransversal:false, wedge:null, slots:[], marks:[], found:[], selections:[], allFound:false, wedgeMode:null, family:'green' }; }
function resize() { const r=canvas.getBoundingClientRect(); canvas.width=r.width*dpr; canvas.height=r.height*dpr; ctx.setTransform(dpr,0,0,dpr,0,0); draw(); }
window.addEventListener('resize', resize);
function point(e) { const r=canvas.getBoundingClientRect(); return {x:e.clientX-r.left,y:e.clientY-r.top}; }
function norm(a) { while(a>Math.PI/2)a-=Math.PI; while(a<-Math.PI/2)a+=Math.PI; return a; }
function lineFor(a,b,color) { const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),ux=dx/len,uy=dy/len,mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2}; return {a:{x:mid.x-ux*240,y:mid.y-uy*240},b:{x:mid.x+ux*240,y:mid.y+uy*240},angle:Math.atan2(uy,ux),color}; }
function segment(line,dash=false) { const u={x:Math.cos(line.angle),y:Math.sin(line.angle)},m={x:(line.a.x+line.b.x)/2,y:(line.a.y+line.b.y)/2}; ctx.save();ctx.strokeStyle=line.color;ctx.lineWidth=2;ctx.globalAlpha=.32;if(dash)ctx.setLineDash([5,7]);ctx.beginPath();ctx.moveTo(m.x-u.x*1000,m.y-u.y*1000);ctx.lineTo(m.x+u.x*1000,m.y+u.y*1000);ctx.stroke();ctx.restore();ctx.save();ctx.strokeStyle=line.color;ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(line.a.x,line.a.y);ctx.lineTo(line.b.x,line.b.y);ctx.stroke();ctx.restore(); }
function circle(p,r,color,fill='#fffefa') { ctx.save();ctx.fillStyle=fill;ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore(); }
function visibleHandle(line) { const w=canvas.clientWidth,h=canvas.clientHeight,b=line.b;if(b.x>=12&&b.x<=w-12&&b.y>=12&&b.y<=h-12)return b;const mid={x:(line.a.x+line.b.x)/2,y:(line.a.y+line.b.y)/2},u={x:Math.cos(line.angle),y:Math.sin(line.angle)},times=[];if(u.x>0)times.push((w-14-mid.x)/u.x);else if(u.x<0)times.push((14-mid.x)/u.x);if(u.y>0)times.push((h-14-mid.y)/u.y);else if(u.y<0)times.push((14-mid.y)/u.y);const t=Math.min(...times.filter(value=>value>0));return {x:mid.x+u.x*t,y:mid.y+u.y*t}; }
function intersection(l1,l2) { const x1=l1.a.x,y1=l1.a.y,x2=l1.b.x,y2=l1.b.y,x3=l2.a.x,y3=l2.a.y,x4=l2.b.x,y4=l2.b.y,d=(x1-x2)*(y3-y4)-(y1-y2)*(x3-x4);if(Math.abs(d)<.0001)return null;const t=((x1-x3)*(y3-y4)-(y1-y3)*(x3-x4))/d;return {x:x1+t*(x2-x1),y:y1+t*(y2-y1)}; }
function turn(a) { a%=Math.PI*2;return a<0?a+Math.PI*2:a; }
function angleDistance(a,b) { const d=turn(a-b);return Math.min(d,Math.PI*2-d); }
function inWedge(p,w) { const dx=p.x-w.x,dy=p.y-w.y,dist=Math.hypot(dx,dy);return dist<=w.r+14&&dist>=8&&turn(Math.atan2(dy,dx)-w.angle)<=w.size+.03; }
function exactAngle(lineAngle,transversalAngle) { let best=null;[lineAngle,lineAngle+Math.PI].forEach(lineRay=>[transversalAngle,transversalAngle+Math.PI].forEach(transRay=>{const ccw=turn(transRay-lineRay),size=ccw<=Math.PI?ccw:Math.PI*2-ccw,start=ccw<=Math.PI?lineRay:transRay;if(!best||size<best.size-.001)best={angle:start,size};}));return best; }
function colourFor(w) { return w.family==='purple'?C.purple:'#758907'; }
function fillFor(w,locked) { if(w.family==='purple')return locked?'rgba(154,98,207,.40)':'rgba(183,132,226,.72)';return locked?'rgba(216,233,118,.43)':'rgba(216,233,118,.75)'; }
function drawWedge(w,locked=false) { const a1=w.angle,a2=w.angle+w.size,c=colourFor(w),selected=w.selected;ctx.save();ctx.translate(w.x,w.y);ctx.fillStyle=selected?'rgba(63,115,201,.54)':fillFor(w,locked);ctx.strokeStyle=selected?C.blue:c;ctx.lineWidth=selected?4:locked?3:2;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,w.r,a1,a2);ctx.closePath();ctx.fill();ctx.stroke();if(w.near&&!locked){ctx.strokeStyle=C.orange;ctx.globalAlpha=.7;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,w.r+8,a1-.07,a2+.07);ctx.stroke();ctx.globalAlpha=1;}if(selected){ctx.strokeStyle=C.blue;ctx.globalAlpha=.45;ctx.lineWidth=6;ctx.beginPath();ctx.arc(0,0,w.r+10,a1-.08,a2+.08);ctx.stroke();ctx.globalAlpha=1;}if(locked&&!state.allFound){ctx.fillStyle=c;ctx.font='700 12px DM Sans';ctx.textAlign='center';ctx.fillText('✓ found',Math.cos((a1+a2)/2)*(w.r+22),Math.sin((a1+a2)/2)*(w.r+22));}else if(!locked){ctx.fillStyle=c;const hp={x:Math.cos((a1+a2)/2)*w.r,y:Math.sin((a1+a2)/2)*w.r};ctx.beginPath();ctx.arc(hp.x,hp.y,7,0,Math.PI*2);ctx.fill();}ctx.restore(); }
function draw() { const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fcfbf7';ctx.fillRect(0,0,w,h);ctx.save();ctx.strokeStyle='rgba(23,45,61,.055)';ctx.lineWidth=1;for(let x=25;x<w;x+=25){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=25;y<h;y+=25){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.restore();state.lines.forEach(l=>segment(l,true));if(state.phase===1&&state.lines[1])circle(visibleHandle(state.lines[1]),11,C.blue);if(state.phase>=2&&state.lines.length===3){const [a,b,t]=state.lines;[intersection(a,t),intersection(b,t)].filter(Boolean).forEach(p=>{ctx.save();ctx.strokeStyle='rgba(63,115,201,.38)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,17,0,Math.PI*2);ctx.stroke();ctx.restore();});if(state.allFound){const handle=visibleHandle(t);circle(handle,12,C.orange);ctx.fillStyle=C.orange;ctx.font='600 10px DM Mono';ctx.textAlign='center';ctx.fillText('rotate',handle.x,handle.y-20);}}if(state.drawStart&&state.pointer){ctx.save();ctx.strokeStyle=C.muted;ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(state.drawStart.x,state.drawStart.y);ctx.lineTo(state.pointer.x,state.pointer.y);ctx.stroke();ctx.restore();}state.marks.forEach(mark=>drawWedge({...mark,selected:state.selections.includes(mark.id)},true));if(state.wedge)drawWedge(state.wedge); }
function setInstruction(step,title,copy) { ui.count.textContent=step;ui.title.textContent=title;ui.copy.textContent=copy; }
let messageTimer;
function say(text,good=false) { clearTimeout(messageTimer);ui.message.textContent=text;ui.message.style.background=good?C.blue:'#17232d';ui.message.classList.add('show');messageTimer=setTimeout(()=>ui.message.classList.remove('show'),2800); }
function reframeCloseParallels() { const [first,second]=state.lines,normal={x:-Math.sin(first.angle),y:Math.cos(first.angle)},one={x:(first.a.x+first.b.x)/2,y:(first.a.y+first.b.y)/2},two={x:(second.a.x+second.b.x)/2,y:(second.a.y+second.b.y)/2},signed=(two.x-one.x)*normal.x+(two.y-one.y)*normal.y,gap=Math.abs(signed),target=Math.min(205,Math.max(150,canvas.clientHeight*.31));if(gap>=target)return false;const direction=signed<0?-1:1,centre={x:canvas.clientWidth/2,y:canvas.clientHeight/2},u={x:Math.cos(first.angle),y:Math.sin(first.angle)},start=[first,second].map(line=>({a:{...line.a},b:{...line.b}})),targets=[-direction*target/2,direction*target/2].map(offset=>{const mid={x:centre.x+normal.x*offset,y:centre.y+normal.y*offset};return {a:{x:mid.x-u.x*240,y:mid.y-u.y*240},b:{x:mid.x+u.x*240,y:mid.y+u.y*240}};}),began=performance.now(),duration=720,animate=now=>{const progress=Math.min(1,(now-began)/duration),ease=1-Math.pow(1-progress,3);[first,second].forEach((line,index)=>{line.a.x=start[index].a.x+(targets[index].a.x-start[index].a.x)*ease;line.a.y=start[index].a.y+(targets[index].a.y-start[index].a.y)*ease;line.b.x=start[index].b.x+(targets[index].b.x-start[index].b.x)*ease;line.b.y=start[index].b.y+(targets[index].b.y-start[index].b.y)*ease;});draw();if(progress<1)requestAnimationFrame(animate);};requestAnimationFrame(animate);return true; }
function finishParallel() { state.phase=2;const reframed=reframeCloseParallels();ui.badge.classList.add('show');ui.labels.forEach(l=>l.style.opacity=1);setInstruction('03 / 03','Draw a transversal','Draw a slanted line across both parallel lines. Keep it between 15° and 75° for a satisfying puzzle.');ui.relationship.textContent='The arrows show equal direction.';say(reframed?'Parallel lines found — gently zooming out to make room.':'Parallel lines found.',true); }
function validTransversal(l) { const angle=Math.abs(norm(l.angle-state.lines[0].angle))*180/Math.PI;return angle>=15&&angle<=75; }
function cloneSlot(slot) { return {id:slot.id,x:slot.x,y:slot.y,angle:slot.angle,size:slot.size,r:slot.r,family:slot.family,vertex:slot.vertex}; }
function familySlots(family) { return state.slots.filter(slot=>slot.family===family); }
function sameFamilyRelation(a,b) { const aKey=a.id.split('-').slice(1).join('-'),bKey=b.id.split('-').slice(1).join('-'),key=[aKey,bKey].sort().join(':');return ({'lower-corresponding:source':'Corresponding Angles','lower-opposite:top-opposite':'Corresponding Angles','source:top-opposite':'Vertically Opposite Angles','lower-corresponding:lower-opposite':'Vertically Opposite Angles','lower-opposite:source':'Alternate Exterior Angles','lower-corresponding:top-opposite':'Alternate Interior Angles'})[key]||'Congruent Angles'; }
function isInterior(slot) { const [top,bottom]=state.lines,normal={x:-Math.sin(top.angle),y:Math.cos(top.angle)},mid=slot.angle+slot.size/2,p={x:slot.x+Math.cos(mid)*20,y:slot.y+Math.sin(mid)*20},topSide=(p.x-top.a.x)*normal.x+(p.y-top.a.y)*normal.y,bottomSide=(p.x-bottom.a.x)*normal.x+(p.y-bottom.a.y)*normal.y;return topSide*bottomSide<=0; }
function relationFor(a,b) { if(a.family===b.family)return {name:sameFamilyRelation(a,b),detail:'same opening, different place.'};if(a.vertex===b.vertex)return {name:'Linear Pair',detail:'adjacent supplementary angles — sum = 180°.'};return {name:isInterior(a)&&isInterior(b)?'Same-side Interior Angles':'Same-side Exterior Angles',detail:'supplementary angles — sum = 180°.'}; }
function updateSelection() { if(state.selections.length<2){ui.relationship.textContent=state.selections.length?'Choose one more marked angle.':'Select any two marked wedges.';return;}const selected=state.selections.map(id=>state.marks.find(mark=>mark.id===id)),result=relationFor(...selected);ui.relationship.textContent=result.name+' — '+result.detail;setInstruction('NAME IT',result.name,result.detail+' Select another pair to compare again.');say(result.name,true); }
function keepConstructionVisible() { const [top,bottom,transversal]=state.lines,points=[intersection(top,transversal),intersection(bottom,transversal)],width=canvas.clientWidth,height=canvas.clientHeight,margin=72,minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y));let dx=0,dy=0;if(minX<margin||maxX>width-margin)dx=width/2-(minX+maxX)/2;if(minY<margin||maxY>height-margin)dy=height/2-(minY+maxY)/2;if(dx||dy)state.lines.forEach(line=>{line.a.x+=dx;line.b.x+=dx;line.a.y+=dy;line.b.y+=dy;}); }
function focusConstruction() { const [top,bottom,transversal]=state.lines,points=[intersection(top,transversal),intersection(bottom,transversal)],centre={x:(points[0].x+points[1].x)/2,y:(points[0].y+points[1].y)/2},relative=points.map(point=>point.y-centre.y),margin=82,desiredY=Math.min(canvas.clientHeight-margin-Math.max(...relative),Math.max(margin-Math.min(...relative),canvas.clientHeight*.42)),dx=canvas.clientWidth*.5-centre.x,dy=desiredY-centre.y;state.lines.forEach(line=>{line.a.x+=dx;line.b.x+=dx;line.a.y+=dy;line.b.y+=dy;}); }
function buildAngleSlots() { const [top,bottom,transversal]=state.lines,topPoint=intersection(top,transversal),bottomPoint=intersection(bottom,transversal),acute=exactAngle(top.angle,transversal.angle),acuteOpposite={angle:turn(acute.angle+Math.PI),size:acute.size},obtuse={angle:turn(acute.angle+acute.size),size:Math.PI-acute.size},obtuseOpposite={angle:turn(obtuse.angle+Math.PI),size:obtuse.size},common={r:52};return [{id:'g-source',family:'green',vertex:'top',x:topPoint.x,y:topPoint.y,...acute,...common},{id:'g-top-opposite',family:'green',vertex:'top',x:topPoint.x,y:topPoint.y,...acuteOpposite,...common},{id:'g-lower-corresponding',family:'green',vertex:'bottom',x:bottomPoint.x,y:bottomPoint.y,...acute,...common},{id:'g-lower-opposite',family:'green',vertex:'bottom',x:bottomPoint.x,y:bottomPoint.y,...acuteOpposite,...common},{id:'p-source',family:'purple',vertex:'top',x:topPoint.x,y:topPoint.y,...obtuse,...common},{id:'p-top-opposite',family:'purple',vertex:'top',x:topPoint.x,y:topPoint.y,...obtuseOpposite,...common},{id:'p-lower-corresponding',family:'purple',vertex:'bottom',x:bottomPoint.x,y:bottomPoint.y,...obtuse,...common},{id:'p-lower-opposite',family:'purple',vertex:'bottom',x:bottomPoint.x,y:bottomPoint.y,...obtuseOpposite,...common}]; }
function refreshAngleGeometry() { state.slots=buildAngleSlots();state.marks=state.marks.map(mark=>{const slot=state.slots.find(item=>item.id===mark.id);return slot?cloneSlot(slot):mark;}); }
function rotateTransversal(p) { const [parallel,,transversal]=state.lines,mid={x:(transversal.a.x+transversal.b.x)/2,y:(transversal.a.y+transversal.b.y)/2},minimum=Math.PI/12,maximum=Math.PI*5/12;let delta=norm(Math.atan2(p.y-mid.y,p.x-mid.x)-parallel.angle),sign=delta<0?-1:1;delta=sign*Math.min(maximum,Math.max(minimum,Math.abs(delta)));transversal.angle=parallel.angle+delta;const length=240;transversal.a={x:mid.x-Math.cos(transversal.angle)*length,y:mid.y-Math.sin(transversal.angle)*length};transversal.b={x:mid.x+Math.cos(transversal.angle)*length,y:mid.y+Math.sin(transversal.angle)*length};refreshAngleGeometry();draw(); }
function activateAngles() { state.phase=3;keepConstructionVisible();focusConstruction();state.slots=buildAngleSlots();startFamily('green'); }
function startFamily(family) { state.family=family;const slots=familySlots(family),seed=slots[0];state.found=[seed.id];state.wedge=cloneSlot(seed);if(family==='green'){setInstruction('EXPLORE','Move the green angle','Move, rotate, and resize the wedge freely. It will only snap when it fits an equal angle exactly.');ui.relationship.textContent='1 of 4 equal green angles found.';say('Explore the equal openings.',true);}else{setInstruction('NEXT DISCOVERY','Find the purple angles','Now move the purple wedge. Find the four angles that complete a straight line with the green ones.');ui.relationship.textContent='Find all 4 purple angles — each is the green angle’s supplement.';say('A new angle family is ready.',true);}draw(); }
function completeFamily() { if(state.family==='green'){startFamily('purple');return;}state.wedge=null;state.allFound=true;setInstruction('MAKE A CONCLUSION','What do the two colours make?','Drag the orange handle on the transversal to explore a new crossing, or select two wedges to name their relationship.');ui.relationship.textContent='All 8 angles found. Drag the orange handle to rotate the transversal.';say('All angle families found — rotate the transversal to explore.',true); }
function reset() { state=freshState();ui.badge.classList.remove('show');ui.labels.forEach(l=>l.style.opacity=0);ui.relationship.textContent='';setInstruction('01 / 03','Draw your first line','Make a long stroke anywhere on the canvas. It will snap into a clean, infinite line.');draw(); }
function undoMatch() { if(!state.marks.length){say('Nothing to undo.');return;}if(state.allFound){state.allFound=false;state.family='purple';}const marks=state.marks.filter(mark=>mark.family===state.family);if(marks.length<=1){say('Nothing to undo in this round.');return;}const last=marks[marks.length-1];state.marks=state.marks.filter(mark=>mark.id!==last.id);state.found=state.marks.filter(mark=>mark.family===state.family).map(mark=>mark.id);state.selections=[];state.wedge=cloneSlot(familySlots(state.family)[0]);ui.relationship.textContent=state.found.length+' of 4 '+state.family+' angles found.';setInstruction(state.found.length+' / 4','Try again','The last match was removed. Rotate and place the wedge precisely.');say('Last match removed.');draw(); }

canvas.addEventListener('pointerdown',e=>{const p=point(e);canvas.setPointerCapture(e.pointerId);if(state.allFound&&state.lines[2]&&Math.hypot(p.x-visibleHandle(state.lines[2]).x,p.y-visibleHandle(state.lines[2]).y)<32){state.draggingTransversal=true;return;}if(state.allFound){const mark=[...state.marks].reverse().find(item=>inWedge(p,item));if(mark){state.selections=state.selections.includes(mark.id)?state.selections.filter(id=>id!==mark.id):[...state.selections.slice(-1),mark.id];updateSelection();draw();return;}}if(state.phase===1&&state.lines[1]&&Math.hypot(p.x-visibleHandle(state.lines[1]).x,p.y-visibleHandle(state.lines[1]).y)<28){state.draggingHandle=true;return;}if(state.wedge){const w=state.wedge,dist=Math.hypot(p.x-w.x,p.y-w.y),mid=w.angle+w.size/2,hp={x:w.x+Math.cos(mid)*w.r,y:w.y+Math.sin(mid)*w.r};if(Math.hypot(p.x-hp.x,p.y-hp.y)<17){state.wedgeMode='rotate';return;}if(Math.abs(dist-w.r)<14){state.wedgeMode='resize';return;}if(dist<w.r){state.wedgeMode='move';state.wedgeOffset={x:p.x-w.x,y:p.y-w.y};return;}}if(state.phase<3){state.drawStart=p;state.pointer=p;draw();}});
canvas.addEventListener('pointermove',e=>{const p=point(e);if(state.draggingTransversal){rotateTransversal(p);return;}if(state.draggingHandle){const l1=state.lines[0],l2=state.lines[1],mid={x:(l2.a.x+l2.b.x)/2,y:(l2.a.y+l2.b.y)/2};let a=Math.atan2(p.y-mid.y,p.x-mid.x);if(Math.abs(norm(a-l1.angle))*180/Math.PI<9)a=l1.angle;const len=240;l2.angle=a;l2.b={x:mid.x+Math.cos(a)*len,y:mid.y+Math.sin(a)*len};l2.a={x:mid.x-Math.cos(a)*len,y:mid.y-Math.sin(a)*len};draw();return;}if(state.wedge&&state.wedgeMode){const q=state.wedge;if(state.wedgeMode==='move'){q.x=p.x-state.wedgeOffset.x;q.y=p.y-state.wedgeOffset.y;}else if(state.wedgeMode==='rotate'){q.angle=Math.atan2(p.y-q.y,p.x-q.x)-q.size/2;}else q.r=Math.max(28,Math.min(100,Math.hypot(p.x-q.x,p.y-q.y)));q.near=familySlots(state.family).filter(slot=>!state.found.includes(slot.id)).some(slot=>Math.hypot(q.x-slot.x,q.y-slot.y)<76&&angleDistance(q.angle,slot.angle)<.18);draw();return;}if(state.drawStart){state.pointer=p;draw();}});
canvas.addEventListener('pointerup',e=>{const p=point(e);if(state.draggingTransversal){state.draggingTransversal=false;say('The wedges adjusted to the new transversal.',true);draw();return;}if(state.draggingHandle){state.draggingHandle=false;const diff=Math.abs(norm(state.lines[1].angle-state.lines[0].angle))*180/Math.PI;if(diff<.5)finishParallel();else say('Keep dragging until the blue line clicks parallel.');draw();return;}if(state.wedgeMode){const w=state.wedge;state.wedgeMode=null;w.near=false;const target=familySlots(state.family).filter(slot=>!state.found.includes(slot.id)).find(slot=>Math.hypot(w.x-slot.x,w.y-slot.y)<52&&angleDistance(w.angle,slot.angle)<.075);if(target){const seed=familySlots(state.family)[0];if(!state.marks.some(mark=>mark.id===seed.id))state.marks.push(cloneSlot(seed));state.marks.push(cloneSlot(target));state.found.push(target.id);if(state.found.length===4)completeFamily();else{state.wedge=cloneSlot(seed);ui.relationship.textContent=state.found.length+' of 4 '+(state.family==='green'?'green':'purple')+' angles found.';setInstruction(state.found.length+' / 4','Keep matching','Move the wedge freely. It will leave a mark only when it fits exactly.');say('Correct — keep looking!',true);}}draw();return;}if(!state.drawStart)return;const start=state.drawStart;state.drawStart=null;state.pointer=null;if(Math.hypot(p.x-start.x,p.y-start.y)<55){say('Make a longer stroke.');draw();return;}const colors=[C.orange,C.blue,C.dark],line=lineFor(start,p,colors[state.lines.length]);if(state.phase===0){state.lines.push(line);state.phase=1;setInstruction('02 / 03','Make a matching line','Draw a second stroke, then drag its blue end handle until it snaps parallel.');ui.labels[0].style.opacity=1;}else if(state.phase===1){const diff=Math.abs(norm(line.angle-state.lines[0].angle))*180/Math.PI;if(diff<8){line.angle=state.lines[0].angle;const mid={x:(line.a.x+line.b.x)/2,y:(line.a.y+line.b.y)/2};line.a={x:mid.x-Math.cos(line.angle)*240,y:mid.y-Math.sin(line.angle)*240};line.b={x:mid.x+Math.cos(line.angle)*240,y:mid.y+Math.sin(line.angle)*240};state.lines.push(line);finishParallel();}else{state.lines.push(line);say('Drag the blue endpoint to make these parallel.');}}else if(state.phase===2){if(!validTransversal(line)){say('Try a clearer slant: between 15° and 75°.');draw();return;}const i1=intersection(state.lines[0],line),i2=intersection(state.lines[1],line);if(!i1||!i2||i1.x<0||i1.x>canvas.clientWidth||i2.x<0||i2.x>canvas.clientWidth||i1.y<0||i1.y>canvas.clientHeight||i2.y<0||i2.y>canvas.clientHeight){say('Make sure your line crosses both lines.');draw();return;}state.lines.push(line);activateAngles();}draw();});
document.getElementById('reset').addEventListener('click',reset);ui.undo.addEventListener('click',undoMatch);state=freshState();resize();reset();
