const canvas = document.getElementById('geometry-canvas');
const ctx = canvas.getContext('2d');
const ui = {
  count: document.getElementById('step-count'), title: document.getElementById('instruction-title'), copy: document.getElementById('instruction-copy'),
  message: document.getElementById('canvas-message'), badge: document.getElementById('parallel-badge'), relationship: document.getElementById('relationship'),
  labels: [...document.querySelectorAll('.canvas-label')]
};
const C = { orange:'#f36f45', blue:'#3f73c9', dark:'#172d3d', lime:'#d8e976', muted:'#9ba7a4' };
let dpr = window.devicePixelRatio || 1;
let state = { lines:[], phase:0, drawStart:null, pointer:null, draggingHandle:false, wedge:null, slots:[], marks:[], found:['source'], selections:[], allFound:false, wedgeMode:null, discovered:false };

function resize() { const r=canvas.getBoundingClientRect(); canvas.width=r.width*dpr; canvas.height=r.height*dpr; ctx.setTransform(dpr,0,0,dpr,0,0); draw(); }
window.addEventListener('resize', resize);
function point(e) { const r=canvas.getBoundingClientRect(); return {x:e.clientX-r.left,y:e.clientY-r.top}; }
function norm(a) { while(a>Math.PI/2)a-=Math.PI; while(a<-Math.PI/2)a+=Math.PI; return a; }
function lineFor(a,b,color) { const dx=b.x-a.x,dy=b.y-a.y; const len=Math.hypot(dx,dy); const ux=dx/len,uy=dy/len; const mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2}; return {a:{x:mid.x-ux*240,y:mid.y-uy*240},b:{x:mid.x+ux*240,y:mid.y+uy*240},angle:Math.atan2(uy,ux),color}; }
function segment(line, dash=false) { const w=canvas.clientWidth,h=canvas.clientHeight; const u={x:Math.cos(line.angle),y:Math.sin(line.angle)}; const m={x:(line.a.x+line.b.x)/2,y:(line.a.y+line.b.y)/2}; ctx.save(); ctx.strokeStyle=line.color; ctx.lineWidth=2; ctx.globalAlpha=.32; if(dash)ctx.setLineDash([5,7]); ctx.beginPath();ctx.moveTo(m.x-u.x*1000,m.y-u.y*1000);ctx.lineTo(m.x+u.x*1000,m.y+u.y*1000);ctx.stroke();ctx.restore(); ctx.save();ctx.strokeStyle=line.color;ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(line.a.x,line.a.y);ctx.lineTo(line.b.x,line.b.y);ctx.stroke();ctx.restore(); }
function circle(p,r,color,fill='#fffefa') { ctx.save();ctx.fillStyle=fill;ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore(); }
function intersection(l1,l2) { const x1=l1.a.x,y1=l1.a.y,x2=l1.b.x,y2=l1.b.y,x3=l2.a.x,y3=l2.a.y,x4=l2.b.x,y4=l2.b.y; const d=(x1-x2)*(y3-y4)-(y1-y2)*(x3-x4); if(Math.abs(d)<.0001)return null; const t=((x1-x3)*(y3-y4)-(y1-y3)*(x3-x4))/d; return {x:x1+t*(x2-x1),y:y1+t*(y2-y1)}; }
function turn(a) { a%=Math.PI*2; return a<0?a+Math.PI*2:a; }
function angleDistance(a,b) { const d=turn(a-b); return Math.min(d,Math.PI*2-d); }
function inWedge(p,w) { const dx=p.x-w.x,dy=p.y-w.y,dist=Math.hypot(dx,dy); if(dist>w.r+14 || dist<8)return false; return turn(Math.atan2(dy,dx)-w.angle)<=w.size+.03; }
function exactAngle(lineAngle, transversalAngle) {
  let best=null;
  [lineAngle,lineAngle+Math.PI].forEach(lineRay=>[transversalAngle,transversalAngle+Math.PI].forEach(transRay=>{
    const ccw=turn(transRay-lineRay), size=ccw<=Math.PI?ccw:Math.PI*2-ccw;
    const start=ccw<=Math.PI?lineRay:transRay;
    if(!best || size<best.size-.001) best={angle:start,size};
  }));
  return best;
}
function drawWedge(w, locked=false, ghost=false) { const a1=w.angle,a2=w.angle+w.size; ctx.save();ctx.translate(w.x,w.y);ctx.fillStyle=ghost?'rgba(216,233,118,.14)':locked?'rgba(216,233,118,.43)':'rgba(216,233,118,.75)';ctx.strokeStyle=ghost?'rgba(117,137,7,.65)':'#758907';ctx.lineWidth=locked?3:2; if(ghost)ctx.setLineDash([5,4]);ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,w.r,a1,a2);ctx.closePath();ctx.fill();ctx.stroke();ctx.setLineDash([]); if(w.selected){ctx.strokeStyle='#3f73c9';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,w.r+9,a1-.08,a2+.08);ctx.stroke();} if(locked){ctx.fillStyle='#758907';ctx.font='700 13px DM Sans';ctx.textAlign='center';ctx.fillText('✓ same angle',Math.cos((a1+a2)/2)*(w.r+24),Math.sin((a1+a2)/2)*(w.r+24));} else {ctx.fillStyle='#758907';const hp={x:Math.cos((a1+a2)/2)*w.r,y:Math.sin((a1+a2)/2)*w.r};ctx.beginPath();ctx.arc(hp.x,hp.y,7,0,Math.PI*2);ctx.fill();}ctx.restore(); }
function draw() { const w=canvas.clientWidth,h=canvas.clientHeight; ctx.clearRect(0,0,w,h); ctx.fillStyle='#fcfbf7';ctx.fillRect(0,0,w,h); ctx.save();ctx.strokeStyle='rgba(23,45,61,.055)';ctx.lineWidth=1; for(let x=25;x<w;x+=25){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=25;y<h;y+=25){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore();
  state.lines.forEach(l=>segment(l,true));
  if(state.phase===1 && state.lines[1]) { circle(state.lines[1].b,10,C.blue); }
  if(state.phase>=2 && state.lines.length===3) { const [a,b,t]=state.lines; const i1=intersection(a,t),i2=intersection(b,t); [i1,i2].filter(Boolean).forEach(p=>{ctx.save();ctx.strokeStyle='rgba(63,115,201,.38)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,17,0,Math.PI*2);ctx.stroke();ctx.restore();}); }
  if(state.drawStart&&state.pointer) {ctx.save();ctx.strokeStyle='#9ba7a4';ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(state.drawStart.x,state.drawStart.y);ctx.lineTo(state.pointer.x,state.pointer.y);ctx.stroke();ctx.restore();}
  state.marks.forEach(mark=>drawWedge({...mark,selected:state.selections.includes(mark.id)},true));
  if(state.wedge) drawWedge(state.wedge);
}
function setInstruction(step,title,copy) { ui.count.textContent=step;ui.title.textContent=title;ui.copy.textContent=copy; }
let messageTimer;
function say(text, good=false) { clearTimeout(messageTimer); ui.message.textContent=text;ui.message.style.background=good?'#3f73c9':'#17232d';ui.message.classList.add('show');messageTimer=setTimeout(()=>ui.message.classList.remove('show'),2800); }
function finishParallel() { state.phase=2;ui.badge.classList.add('show');ui.labels.forEach(l=>l.style.opacity=1);setInstruction('03 / 03','Draw a transversal','Draw a slanted line across both parallel lines. Keep it between 15° and 75° for a satisfying puzzle.');ui.relationship.textContent='The arrows show equal direction.';say('Parallel lines found.',true); }
function validTransversal(l) { const angle=Math.abs(norm(l.angle-state.lines[0].angle))*180/Math.PI; return angle>=15&&angle<=75; }
function cloneSlot(slot) { return {id:slot.id,x:slot.x,y:slot.y,angle:slot.angle,size:slot.size,r:slot.r}; }
function relationFor(a,b) { const key=[a,b].sort().join(':'); return ({'lower-corresponding:source':'Corresponding Angles','lower-opposite:top-opposite':'Corresponding Angles','source:top-opposite':'Vertically Opposite Angles','lower-corresponding:lower-opposite':'Vertically Opposite Angles','lower-opposite:source':'Alternate Exterior Angles','lower-corresponding:top-opposite':'Alternate Interior Angles'})[key] || 'Congruent Angles'; }
function updateSelection() { if(state.selections.length<2){ui.relationship.textContent=state.selections.length?'Choose one more marked angle.':'Select any two green marks.';return;} const name=relationFor(state.selections[0],state.selections[1]); ui.relationship.textContent=name+' — same opening, different place.'; setInstruction('NAME IT',name,'You found this relationship by matching the exact opening first. Select another pair to compare again.'); say(name,true); }
function keepConstructionVisible() { const [top,bottom,transversal]=state.lines, points=[intersection(top,transversal),intersection(bottom,transversal)]; const width=canvas.clientWidth,height=canvas.clientHeight,margin=72; let minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y)); let dx=0,dy=0; if(minX<margin || maxX>width-margin) dx=width/2-(minX+maxX)/2; if(minY<margin || maxY>height-margin) dy=height/2-(minY+maxY)/2; if(dx||dy) state.lines.forEach(line=>{line.a.x+=dx;line.b.x+=dx;line.a.y+=dy;line.b.y+=dy;}); }
function activateAngles() { state.phase=3; keepConstructionVisible(); const [top,bottom,transversal]=state.lines; const topPoint=intersection(top,transversal), bottomPoint=intersection(bottom,transversal), shape=exactAngle(top.angle,transversal.angle), opposite={angle:turn(shape.angle+Math.PI),size:shape.size}; const common={r:52}; state.slots=[{id:'source',x:topPoint.x,y:topPoint.y,...shape,...common},{id:'top-opposite',x:topPoint.x,y:topPoint.y,...opposite,...common},{id:'lower-corresponding',x:bottomPoint.x,y:bottomPoint.y,...shape,...common},{id:'lower-opposite',x:bottomPoint.x,y:bottomPoint.y,...opposite,...common}]; state.wedge=cloneSlot(state.slots[0]); state.found=['source']; setInstruction('EXPLORE','Move the angle','Move, rotate, and resize the wedge freely. It will only snap when it fits an equal angle exactly.');ui.relationship.textContent='1 of 4 congruent angles found.';say('Explore the equal openings.',true);draw(); }
function reset() { state={lines:[],phase:0,drawStart:null,pointer:null,draggingHandle:false,wedge:null,slots:[],marks:[],found:['source'],selections:[],allFound:false,wedgeMode:null,discovered:false};ui.badge.classList.remove('show');ui.labels.forEach(l=>l.style.opacity=0);ui.relationship.textContent='';setInstruction('01 / 03','Draw your first line','Make a long stroke anywhere on the canvas. It will snap into a clean, infinite line.');draw(); }
canvas.addEventListener('pointerdown',e=>{const p=point(e);canvas.setPointerCapture(e.pointerId); if(state.allFound){const mark=[...state.marks].reverse().find(item=>inWedge(p,item));if(mark){state.selections=state.selections.includes(mark.id)?state.selections.filter(id=>id!==mark.id):[...state.selections.slice(-1),mark.id];updateSelection();draw();return;}} if(state.phase===1&&state.lines[1]&&Math.hypot(p.x-state.lines[1].b.x,p.y-state.lines[1].b.y)<25){state.draggingHandle=true;return;} if(state.wedge){const w=state.wedge,dist=Math.hypot(p.x-w.x,p.y-w.y), mid=w.angle+w.size/2, hp={x:w.x+Math.cos(mid)*w.r,y:w.y+Math.sin(mid)*w.r};if(Math.hypot(p.x-hp.x,p.y-hp.y)<17){state.wedgeMode='rotate';return;}if(Math.abs(dist-w.r)<14){state.wedgeMode='resize';return;}if(dist<w.r){state.wedgeMode='move';state.wedgeOffset={x:p.x-w.x,y:p.y-w.y};return;}} if(state.phase<3){state.drawStart=p;state.pointer=p;draw();}});
canvas.addEventListener('pointermove',e=>{const p=point(e); if(state.draggingHandle){const l1=state.lines[0],l2=state.lines[1],mid={x:(l2.a.x+l2.b.x)/2,y:(l2.a.y+l2.b.y)/2};let a=Math.atan2(p.y-mid.y,p.x-mid.x);if(Math.abs(norm(a-l1.angle))*180/Math.PI<9)a=l1.angle;const len=240;l2.angle=a;l2.b={x:mid.x+Math.cos(a)*len,y:mid.y+Math.sin(a)*len};l2.a={x:mid.x-Math.cos(a)*len,y:mid.y-Math.sin(a)*len};draw();return;} if(state.wedge&&state.wedgeMode){const q=state.wedge;if(state.wedgeMode==='move'){q.x=p.x-state.wedgeOffset.x;q.y=p.y-state.wedgeOffset.y;} else if(state.wedgeMode==='rotate'){q.angle=Math.atan2(p.y-q.y,p.x-q.x)-q.size/2;}else q.r=Math.max(28,Math.min(100,Math.hypot(p.x-q.x,p.y-q.y)));draw();return;} if(state.drawStart){state.pointer=p;draw();}});
canvas.addEventListener('pointerup',e=>{const p=point(e); if(state.draggingHandle){state.draggingHandle=false; const diff=Math.abs(norm(state.lines[1].angle-state.lines[0].angle))*180/Math.PI;if(diff<.5)finishParallel();else say('Keep dragging until the blue line clicks parallel.');draw();return;} if(state.wedgeMode){const w=state.wedge;state.wedgeMode=null;if(!state.allFound){const target=state.slots.filter(slot=>!state.found.includes(slot.id)).find(slot=>Math.hypot(w.x-slot.x,w.y-slot.y)<76&&angleDistance(w.angle,slot.angle)<.13);if(target){if(!state.marks.some(mark=>mark.id==='source'))state.marks.push(cloneSlot(state.slots[0]));state.marks.push(cloneSlot(target));state.found.push(target.id);if(state.found.length===4){state.wedge=null;state.allFound=true;ui.relationship.textContent='All 4 congruent angles found! Select any two green marks.';setInstruction('ALL FOUND','All congruent angles found','Now select any two green wedges. Their geometric relationship will appear here.');say('All congruent angles found!',true);}else{state.wedge=cloneSlot(state.slots[0]);ui.relationship.textContent=state.found.length+' of 4 congruent angles found.';setInstruction(state.found.length+' / 4','Keep matching','Move the wedge freely. It will leave a mark only when it fits exactly.');say('Correct — keep looking!',true);}}}draw();return;} if(!state.drawStart)return; const start=state.drawStart;state.drawStart=null;state.pointer=null;if(Math.hypot(p.x-start.x,p.y-start.y)<55){say('Make a longer stroke.');draw();return;} const colors=[C.orange,C.blue,C.dark];const line=lineFor(start,p,colors[state.lines.length]);if(state.phase===0){state.lines.push(line);state.phase=1;setInstruction('02 / 03','Make a matching line','Draw a second stroke, then drag its blue end handle until it snaps parallel.');ui.labels[0].style.opacity=1;}
else if(state.phase===1){const diff=Math.abs(norm(line.angle-state.lines[0].angle))*180/Math.PI; if(diff<8){line.angle=state.lines[0].angle;const mid={x:(line.a.x+line.b.x)/2,y:(line.a.y+line.b.y)/2};line.a={x:mid.x-Math.cos(line.angle)*240,y:mid.y-Math.sin(line.angle)*240};line.b={x:mid.x+Math.cos(line.angle)*240,y:mid.y+Math.sin(line.angle)*240};state.lines.push(line);finishParallel();}else {state.lines.push(line);say('Drag the blue endpoint to make these parallel.');}}
else if(state.phase===2){if(!validTransversal(line)){say('Try a clearer slant: between 15° and 75°.');draw();return;}const i1=intersection(state.lines[0],line),i2=intersection(state.lines[1],line);if(!i1||!i2||i1.x<0||i1.x>canvas.clientWidth||i2.x<0||i2.x>canvas.clientWidth||i1.y<0||i1.y>canvas.clientHeight||i2.y<0||i2.y>canvas.clientHeight){say('Make sure your line crosses both lines.');draw();return;}state.lines.push(line);activateAngles();}draw(); });
document.getElementById('reset').addEventListener('click',reset); resize(); reset();
